meta:
  model_name: deit_small
  master_port: 8888
  load_checkpoint: true
  training: false
  copy_data: false
  device: cuda:0
data:
  root_path: .
  image_folder: imagenet
  num_classes: 1000
optimization:
  weight_decay: 0.0
  lr: 6.4
  epochs: 100
  num_blocks: 1
  normalize: true
logging:
  folder: checkpoint/msn_logs/
  write_tag: msn-lineval-experiment-1
  pretrain_path: checkpoint/msn_os_logs/vitl16_600ep.pth.tar
